version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/judge0:1.13.0
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    env_file:
      - judge0.conf

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    privileged: true
    <<: *default-logging
    restart: always
    env_file:
      - judge0.conf

  db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - /var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - /data
    <<: *default-logging
    restart: always
